[workspace]
resolver = "2"
members = ["crates/core", "crates/mcp"]

[workspace.package]
version = "0.16.0"
edition = "2024"
rust-version = "1.85"
authors = ["Yutaka Nishimura"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/ynishi/mini-app-mcp"

[workspace.dependencies]
mini-app-core = { path = "crates/core", version = "0.16.0" }
